#!/bin/bash


# Autostart
pkill picom
pkill sxhkd
pkill batterywarn
pkill greenclip
pkill spicetify
sleep 0.1

~/bin/batterywarn &
picom --config /home/afterless/.config/picom/picom.conf -b &

greenclip daemon &
spicetify &

setxkbmap -model pc105 -layout us &
sxhkd &
wal -R -o wal-set &
xsetroot -cursor_name left_ptr &

# Workspaces
if xrandr -q | grep 'DP1 disconnected'; then
  xrandr --output eDP1 --mode 2560x1440
  bspc monitor eDP1 -d web code media edit graphics other
else
  xrandr --output DP1 --mode 3840x2160
  bspc monitor DP1 -d web code media edit graphics other
fi

sh /home/afterless/.config/polybar/launch.sh &

# Source the colors
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"


# Use the line below if you are on bspwm >= 0.9.4

#bspc config presel_feedback_color "$color1"
bspc config presel_border_color "$color1"


# Borders and Gaps
bspc config border_radius       20
bspc config border_width        3.5
bspc config window_gap          25

bspc config bottom_padding 25
bspc config top_padding 10
bspc config left_padding 10
bspc config right_padding 10

bspc config split_ratio          0.50
#bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config click_to_focus       true
bspc config pointer_motion_interval 0

# Rules

bspc config external_rules_command "$(which /home/afterless/.config/bspwm/bspwm-rules)"

bspc rule -a TelegramDesktop desktop="web" follow=off
bspc rule -a Subl3 desktop="code" follow=off
bspc rule -a mpv desktop="media" state=floating follow=on
bspc rule -a Gimp-2.10 desktop="graphics" follow=on
bspc rule -a Transmission-gtk desktop="other" state=floating follow=on
bspc rule -a discord desktop="other" state=pseudo_tiled follow=off

bspc rule -a Sxiv state=floating
bspc rule -a Xarchiver state=floating
bspc rule -a Leafpad state=floating
bspc rule -a Pcmanfm state=floating focus=on
bspc rule -a URxvt state=floating
bspc rule -a feh state=floating
